# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift', '~>3.16.1'

  # Pods for PhotoSearch

  target 'PhotoSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoSearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
